{% set version = "1.1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stable/stable_{{ version }}.tar.gz
  sha256: 2238788a35b5aa9e175ad7b92348640c3dcad68b6ab0a0bc04aeec9084d29da4

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rmutil                   # [build_platform != target_platform]
    - r-stabledist               # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rmutil
    - r-stabledist
  run:
    - r-base
    - r-rmutil
    - r-stabledist

test:
  commands:
    - $R -e "library('stable')"           # [not win]
    - "\"%R%\" -e \"library('stable')\""  # [win]

about:
  home: http://www.commanster.eu/rcode.html
  license: GPL-2.0-or-later
  summary: Density, distribution, quantile and hazard functions of a stable variate; generalized regression models for the parameters of a stable distribution. See the README for how to make equivalent calls to those of 'stabledist'. See github for Journal article.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: stable
# Version: 1.1.4
# Title: Probability Functions and Generalized Regression Models for Stable Distributions
# Authors@R: c( person("Bruce", "Swihart", email="bruce.swihart@gmail.com", role=c("cre", "aut")), person("Jim"  , "Lindsey", email="jlindsey@gen.unimaas.nl", role="aut", comment="Jim created this package, Bruce is maintaining the CRAN version"), person("Philippe", "Lambert", email="phlambert@stat.ucl.ac.be", role="aut") )
# Imports: stabledist
# Depends: R (>= 1.4), rmutil
# Description: Density, distribution, quantile and hazard functions of a stable variate; generalized regression models for the parameters of a stable distribution. See the README for how to make equivalent calls to those of 'stabledist'. See github for Journal article.
# License: GPL (>= 2)
# URL: http://www.commanster.eu/rcode.html
# BugReports: https://github.com/swihart/stable/issues
# Encoding: UTF-8
# LazyData: true
# LazyLoad: true
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2019-02-04 18:54:26 UTC; swihartbj
# Author: Bruce Swihart [cre, aut], Jim Lindsey [aut] (Jim created this package, Bruce is maintaining the CRAN version), Philippe Lambert [aut]
# Maintainer: Bruce Swihart <bruce.swihart@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-04 19:20:03 UTC
