appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: q87XyZmAkwUYOWU99IypC/aGz/Knt2zzQaeY2c1KauzzQYXizfJjy9DxlmM76gQpW94UFmHQNaHDvB4EaFuzmW94L8zvzSlQziPm1HrqItbrD+roiIrzw5w1L+F51/u+PXsr4GOAiHYOi0i1GShU78B9iuFWjyx87UTCNFf1e5XYGQaXbr7lkNvAyxu33GU9DH0Eefy2jvrnDANqh7bI1ci1iDWPZFTghcKis4+hIeksR0Booi8lm5kv3zetugFz7ujhvHrhzkfS/hdUNtv5kuiwDsxv1IDzOKxnnt0CrvDWv9BYOp5cBoRIvue7MlVcT1qeffAuWvP7iBgmqBp2xU3RwYIGdOM0DbaoVl0VC4L3IDnbaF5EDgiyxaFDla15wEexm6z56Kvbwohi4nVmlUPUnnM5IjBXjIU3t+2RRsi5UZVb04tmo77pQdnNwREInxzikXOyIhwAV045WuKrix0vRY/ksA/ixv6rHwHK2cpsCr8a9EZPDJrjdy858YHqlfwjZ8sir3pLSpxZtLcbn+3pzccxcMS5RHWXQvepwX9yU6fSHiH7zNm/KeIKEdAG6Wr/CpONVEwp1XAX8aPYHw07lJRYZw1sfBdiiR5Kn3tmiV7+r8K5fR1YaLExB7qPx5eqR0JLnfKZ0oVNYnrieI+x4syotrRYuevIB8QJbLk=
conda_forge_output_validation: false
